export const SKILL_SAMPLES: Record<string, Record<string, unknown>> = {
  "email-gen": {
    first_name: "Sarah",
    last_name: "Chen",
    title: "VP Engineering",
    company_name: "Lattice",
    industry: "HR Tech / SaaS",
    signal_type: "funding",
    signal_detail: "Series D — $175M led by Tiger Global",
    client_slug: "twelve-labs",
  },
  "icp-scorer": {
    first_name: "Marcus",
    last_name: "Rivera",
    title: "Head of Data",
    company_name: "Snowflake",
    industry: "Cloud Data / SaaS",
    employee_count: 5000,
    technologies: "Spark, dbt, Airflow",
    signal_type: "job_posting",
    signal_detail: "Hiring 3 ML engineers",
  },
  "angle-selector": {
    first_name: "Emily",
    last_name: "Park",
    title: "CTO",
    company_name: "Figma",
    industry: "Design Tools / SaaS",
    signal_type: "product_launch",
    signal_detail: "Launched AI-powered design assistant",
    client_slug: "twelve-labs",
  },
  "linkedin-note": {
    first_name: "James",
    last_name: "Okafor",
    title: "Director of Sales",
    company_name: "Gong",
    signal_type: "promotion",
    signal_detail: "Promoted from Senior Manager",
    client_slug: "twelve-labs",
  },
  "objection-handler": {
    objection: "We already use a competitor for this",
    first_name: "Lisa",
    title: "VP Marketing",
    company_name: "HubSpot",
    client_slug: "twelve-labs",
  },
  "meeting-prep": {
    first_name: "David",
    last_name: "Kim",
    title: "CEO",
    company_name: "Notion",
    meeting_type: "discovery",
    meeting_notes: "Inbound from website demo request",
    client_slug: "twelve-labs",
  },
  "follow-up": {
    first_name: "Rachel",
    last_name: "Torres",
    title: "Head of Partnerships",
    company_name: "Stripe",
    meeting_summary: "Discussed API integration timeline, interested in Q2 pilot",
    action_items: "Send SOW draft, schedule technical deep-dive",
    client_slug: "twelve-labs",
  },
  "campaign-brief": {
    campaign_name: "Q2 AI Infrastructure Push",
    target_persona: "VP Engineering at Series B+ SaaS companies",
    value_prop: "Reduce video search latency by 90% with multimodal AI",
    channels: "LinkedIn, Email",
    client_slug: "twelve-labs",
  },
  "quality-gate": {
    email_subject: "Quick question about your video pipeline",
    email_body:
      "Hi Sarah, noticed Lattice just closed your Series D — congrats! With the team scaling, curious if video content search has come up as a pain point. We helped Notion cut their search latency by 90%. Worth a 15-min chat?",
    first_name: "Sarah",
    company_name: "Lattice",
  },
};

export const MODELS = ["opus", "sonnet", "haiku"] as const;
export type Model = (typeof MODELS)[number];

export const SKILL_FIELDS: Record<string, string[]> = {
  "email-gen": [
    "first_name",
    "last_name",
    "title",
    "company_name",
    "industry",
    "signal_type",
    "signal_detail",
    "client_slug",
  ],
  "icp-scorer": [
    "first_name",
    "last_name",
    "title",
    "company_name",
    "industry",
    "employee_count",
    "technologies",
    "signal_type",
    "signal_detail",
  ],
  "angle-selector": [
    "first_name",
    "last_name",
    "title",
    "company_name",
    "industry",
    "signal_type",
    "signal_detail",
    "client_slug",
  ],
  "linkedin-note": [
    "first_name",
    "last_name",
    "title",
    "company_name",
    "signal_type",
    "signal_detail",
    "client_slug",
  ],
  "objection-handler": [
    "objection",
    "first_name",
    "title",
    "company_name",
    "client_slug",
  ],
  "meeting-prep": [
    "first_name",
    "last_name",
    "title",
    "company_name",
    "meeting_type",
    "meeting_notes",
    "client_slug",
  ],
  "follow-up": [
    "first_name",
    "last_name",
    "title",
    "company_name",
    "meeting_summary",
    "action_items",
    "client_slug",
  ],
  "campaign-brief": [
    "campaign_name",
    "target_persona",
    "value_prop",
    "channels",
    "client_slug",
  ],
  "quality-gate": [
    "email_subject",
    "email_body",
    "first_name",
    "company_name",
  ],
};
